<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Preschool Scheduling App</title>
</head>
<body>
<#include "navbar.ftlh">
<h1>Welcome to the Preschool Scheduling App</h1>
<p>Choose an option below:</p>
<ul>
    <li><a href="/teacherView">View Teachers</a></li>
    <li><a href="/addTeacher">Add New Teacher</a></li>
    <li><a href="/roomView">View Rooms</a></li>
    <li><a href="/addRoom">Add New Room</a></li>
    <li><a href="/viewSchedules">View Schedules</a></li>
</ul>
</body>
</html>
